
[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [ 
    { key = "F11", action = "ToggleFullscreen" },

    { key = "V", mods = "Control", action = "Paste" },
    { key = "C", mods = "Control", action = "Copy" },
    { key = "C", mods = "Control|Shift", chars = "\u0003" } 
]

[window]
title = "Terminal"
#startup_mode = "Fullscreen"
opacity = 0.9
blur = true

[mouse]
hide_when_typing = true

[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

